# Site settings
title: Neuroascent
email: neuroascent@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bringing your ideas to life with Custom Machine Learning Solutions 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://neuroascent.ml/" # the base hostname & protocol for your site
twitter_username: neuroascent
github_username:  neuroascent

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"